<?php include $_SERVER['DOCUMENT_ROOT'] . "/includes/header.php"; ?>
<?php include $_SERVER['DOCUMENT_ROOT'] . "/includes/MenuSAdmin.php"; ?>
<?php include $_SERVER['DOCUMENT_ROOT'] . "/includes/SAdmin/dashSAdmin.php"; ?>
<?php include $_SERVER['DOCUMENT_ROOT'] . "/includes/MenuMusicAdmin.php"; ?>
<?php include $_SERVER['DOCUMENT_ROOT'] . "/includes/MusicAdmin/dashMusicAdmin.php"; ?>
<?php include $_SERVER['DOCUMENT_ROOT'] . "/includes/MenuPlaylistAdmin.php"; ?>
<?php include $_SERVER['DOCUMENT_ROOT'] . "/includes/PlaylistAdmin/dashPlaylistAdmin.php"; ?>
<?php include $_SERVER['DOCUMENT_ROOT'] . "/includes/MenuTicketAdmin.php"; ?>
<?php include $_SERVER['DOCUMENT_ROOT'] . "/includes/TicketAdmin/dashTicketAdmin.php"; ?>
<?php include $_SERVER['DOCUMENT_ROOT'] . "/includes/footer.php"; ?>